package test.proje;
// Generated Jul 14, 2017 10:55:17 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Kisiler generated by hbm2java
 */
@Entity
@Table(name="kisiler"
    ,catalog="hib_test_db"
)
public class Kisiler  implements java.io.Serializable {


     private Integer id;
     private String ad;
     private String soyad;
     private Integer yas;

    public Kisiler() {
    }

    public Kisiler(String ad, String soyad, Integer yas) {
       this.ad = ad;
       this.soyad = soyad;
       this.yas = yas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ad")
    public String getAd() {
        return this.ad;
    }
    
    public void setAd(String ad) {
        this.ad = ad;
    }

    
    @Column(name="soyad")
    public String getSoyad() {
        return this.soyad;
    }
    
    public void setSoyad(String soyad) {
        this.soyad = soyad;
    }

    
    @Column(name="yas")
    public Integer getYas() {
        return this.yas;
    }
    
    public void setYas(Integer yas) {
        this.yas = yas;
    }




}


